version: "3.8"
services:
  nt2mqtt:
    image: nt2mqtt
    build: .
    restart: unless-stopped
    depends_on:
      - mqtt
      - grafana

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./conf/grafana.ini:/etc/grafana.ini
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
  
volumes:
  grafana: