version: "3.8"
services:
  nt2mqtt:
    image: nt2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    restart: unless-stopped

  influxdb:
    image: influxdb:2.6.1
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=NT2MQTT
      - DOCKER_INFLUXDB_INIT_BUCKET=main
      - DOCKER_INFLUXDB_INIT_RETENTION=1m
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=abcdef123456!
    volumes:
      - influx-data:/var/lib/influxdb2
  
volumes:
  grafana-data:
  influx-data: